### ISSUE TITLE
wikiextractor raise BdbQuit

### ISSUE THREAD

**Issue by saleelirenyun** [hpcaitech/ColossalAI-Examples#108]
### 🐛 Describe the bug

Hi All,
When I run the code in language Bert # extractmodule 
_wikiextractor --json enwiki-latest-pages-articles.xml.bz2_
I got _raise BdbQuit_, this seems to be solved in [here](https://github.com/NVIDIA/DeepLearningExamples/issues/1091) , by changing the version of wikiextractor to 3.0.4
But after that, the example code couldn't work due to 3.0.4 does not support _--json_

**Comment by FrankLeeeee** [comment]
Hi, I have not met this issue before. Can you provide the versions of wikiextractor you tried?

**Comment by saleelirenyun** [comment]
> Hi, I have not met this issue before. Can you provide the versions of wikiextractor you tried?

Hi, the original and default is 3.0.6, which would raise BdbQuit.

When use 3.0.4, this would be solved, but unable to _--json_ since 3.0.4 doesn't support this command.

**Comment by binmakeswell** [comment]
Hi @saleelirenyun  We have updated the preprocessing, you can try it, thanks.
[preprocessing](https://github.com/hpcaitech/ColossalAI-Examples/tree/main/language/bert/preprocessing)
