### ISSUE TITLE
BERT示例运行错误，ColossalAI-Examples/language/bert/sequene_parallel/

### ISSUE THREAD

**Issue by ZXM1063694570** [hpcaitech/ColossalAI-Examples#158]
### 🐛 Describe the bug

使用了最新提供的Dockerhub上的镜像0.1.8，但是在运行BERT序列并行案例：ColossalAI-Examples/language/bert/sequene_parallel/时候仍不能正常运行，提示缺少相关包：
Traceback (most recent call last):
  File "/workspace/ColossalAI-Examples/language/bert/sequene_parallel/train.py", line 10, in <module>
    from model.bert import BertForPretrain
  File "/workspace/ColossalAI-Examples/language/bert/sequene_parallel/model/bert.py", line 12, in <module>
    from colossalai.builder.pipeline import partition_uniform
ModuleNotFoundError: No module named 'colossalai.builder.pipeline'

![XI 7HJD3ZJY0X1W2RW W}6Q](https://user-images.githubusercontent.com/65949265/180438055-5525967b-0cc1-4b70-89aa-739e55f12c16.png)

### Environment

docker镜像：docker pull hpcaitech/colossalai:0.1.8

**Comment by tianboh** [comment]
I have met this error as well. Use ```from colossalai.pipeline.utils import partition_uniform``` instead.

**Comment by ZXM1063694570** [comment]
> 我也遇到过这个错误。改为使用`from colossalai.pipeline.utils import partition_uniform`。

It worked. Thank you
