### ISSUE TITLE
Personal Dataset Preprocessing

### ISSUE THREAD

**Issue by Lobskodax** [hpcaitech/ColossalAI-Examples#24]
If I want to use my own dataset to train the gpt-2 model, the format is TXT, with one sentence per line, how can I modify the data preprocessing code to make it match and run normally.

**Comment by FrankLeeeee** [comment]
Hi, did you figure out how?

**Comment by FrankLeeeee** [comment]
Hi, I will close this issue for now. If you have difficulty build your own dataset, welcome to re-open this issue. Thanks~
