### ISSUE TITLE
WRONG URL in GPT README

### ISSUE THREAD

**Issue by Wesley-Jzy** [hpcaitech/ColossalAI-Examples#44]
### 🐛 Describe the bug

The link [openwebtext](https://github.com/hpcaitech/ColossalAI-Examples/blob/main/language/gpt/tools/openwebtext) in gpt README dosen't exist.

**Comment by FrankLeeeee** [comment]
Hi @Wesley-Jzy , that sentence is no longer valid and I have removed it in #45 .
