### ISSUE TITLE
ZeRO 2 configuration example

### ISSUE THREAD

**Issue by CHN-ChenYi** [hpcaitech/ColossalAI-Examples#71]
### 📚 The doc issue

The gpt2 zero2 example was removed after the new API was introduced.
But I don't know how to not offload the model.
I've tried removing `model_config` or setting `offload_config` to `None`/`gpu`/`cuda`, but neither of them works.

**Comment by binmakeswell** [comment]
Hi @CHN-ChenYi , we have update the example and tutorial, you can directly use zero, and do not need to set level 2.

https://github.com/hpcaitech/ColossalAI-Examples/tree/main/features/zero
https://www.colossalai.org/docs/features/zero_redundancy_and_zero_offload
